name: flaunch
description: A CLI tool to set up Flutter projects quickly with predefined structures, dependencies, and boilerplate code.
version: 1.0.0+3
repository: https://github.com/Uvais-Mohammad/flaunch
homepage: https://github.com/Uvais-Mohammad/flaunch

environment:
  sdk: ^3.6.2

executables:
  flaunch:

dependencies:
  args: ^2.4.2
  pub_semver: ^2.1.5

dev_dependencies:
  test: ^1.24.0