name: flutter_wizard
description: A CLI tool to set up Flutter projects quickly with predefined structures, dependencies, and boilerplate code.
version: 1.0.0
repository: https://github.com/Uvais-Mohammad/flutter_wizard
homepage: https://github.com/Uvais-Mohammad/flutter_wizard

environment:
  sdk: ^3.6.2

executables:
  flutter_wizard:

dependencies:
  args: ^2.4.2

dev_dependencies:
  test: ^1.24.0